# Generated by Django 5.1.5 on 2025-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='doctor_images/default.jpg', upload_to='doctor_images/'),
        ),
    ]
