# Generated by Django 5.1.5 on 2025-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackhealth',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackhealth',
            name='date',
            field=models.DateField(),
        ),
    ]
