# Generated by Django 5.1.5 on 2025-01-24 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_healthdata_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthData',
            new_name='TrackHealth',
        ),
    ]
