# Generated by Django 5.1.5 on 2025-01-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_healthdata_trackhealth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackHealth',
        ),
    ]
