# Generated by Django 5.1.5 on 2025-01-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
